/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.produto;

import view.produto.Produtos;
import com.sun.jdi.InvalidTypeException;
import javax.swing.JOptionPane;
import model.Produto;

/**
 *
 * @author kauan
 */
public class CadastroProdutos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroProdutos.class.getName());

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroProdutosPanel = new javax.swing.JPanel();
        NomeField = new javax.swing.JTextField();
        PrecoField = new javax.swing.JTextField();
        QntField = new javax.swing.JTextField();
        NomeLabel = new javax.swing.JLabel();
        PrecoLabel = new javax.swing.JLabel();
        QntLabel = new javax.swing.JLabel();
        CadastrarButton = new javax.swing.JButton();
        TituloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CadastroProdutosPanel.setBackground(new java.awt.Color(206, 212, 218));

        NomeField.setBackground(new java.awt.Color(233, 236, 239));

        PrecoField.setBackground(new java.awt.Color(233, 236, 239));

        QntField.setBackground(new java.awt.Color(233, 236, 239));

        NomeLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NomeLabel.setForeground(new java.awt.Color(52, 58, 64));
        NomeLabel.setText("Nome:");

        PrecoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PrecoLabel.setForeground(new java.awt.Color(52, 58, 64));
        PrecoLabel.setText("Preço:");

        QntLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        QntLabel.setForeground(new java.awt.Color(52, 58, 64));
        QntLabel.setText("Quantidade:");

        CadastrarButton.setBackground(new java.awt.Color(233, 236, 239));
        CadastrarButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CadastrarButton.setForeground(new java.awt.Color(52, 58, 64));
        CadastrarButton.setText("Cadastrar");
        CadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarButtonActionPerformed(evt);
            }
        });

        TituloLabel.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(52, 58, 64));
        TituloLabel.setText("Cadastrar Produto");

        javax.swing.GroupLayout CadastroProdutosPanelLayout = new javax.swing.GroupLayout(CadastroProdutosPanel);
        CadastroProdutosPanel.setLayout(CadastroProdutosPanelLayout);
        CadastroProdutosPanelLayout.setHorizontalGroup(
            CadastroProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroProdutosPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(CadastroProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastroProdutosPanelLayout.createSequentialGroup()
                        .addGroup(CadastroProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeLabel)
                            .addComponent(PrecoLabel)
                            .addComponent(QntLabel))
                        .addGap(72, 72, 72)
                        .addGroup(CadastroProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PrecoField)
                            .addComponent(NomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(QntField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroProdutosPanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(TituloLabel)
                .addGap(182, 182, 182))
        );
        CadastroProdutosPanelLayout.setVerticalGroup(
            CadastroProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroProdutosPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TituloLabel)
                .addGap(77, 77, 77)
                .addGroup(CadastroProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeLabel))
                .addGap(18, 18, 18)
                .addGroup(CadastroProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecoLabel))
                .addGap(18, 18, 18)
                .addGroup(CadastroProdutosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QntField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QntLabel))
                .addGap(18, 18, 18)
                .addComponent(CadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        NomeField.getAccessibleContext().setAccessibleName("Campo nome");
        NomeField.getAccessibleContext().setAccessibleDescription("Campo para informar o nome do produto");
        PrecoField.getAccessibleContext().setAccessibleName("Campo preço");
        PrecoField.getAccessibleContext().setAccessibleDescription("Campo para informar o preço do produto");
        QntField.getAccessibleContext().setAccessibleName("Campo quantidade");
        QntField.getAccessibleContext().setAccessibleDescription("Campo para informar a quantidade de produtos em estoque");
        CadastrarButton.getAccessibleContext().setAccessibleName("Botão cadastrar");
        CadastrarButton.getAccessibleContext().setAccessibleDescription("Botão para finalizar o cadastro do produto");
        TituloLabel.getAccessibleContext().setAccessibleDescription("Titulo da tela");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastroProdutosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastroProdutosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        // TODO add your handling code here:
        if(cadastrar()){
            this.dispose();
        }
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroProdutos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JPanel CadastroProdutosPanel;
    private javax.swing.JTextField NomeField;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField PrecoField;
    private javax.swing.JLabel PrecoLabel;
    private javax.swing.JTextField QntField;
    private javax.swing.JLabel QntLabel;
    private javax.swing.JLabel TituloLabel;
    // End of variables declaration//GEN-END:variables
  
    boolean cadastrar(){
    try{
            String nome = NomeField.getText();
            double preco = Double.parseDouble(PrecoField.getText());
            int quantidade = Integer.parseInt(QntField.getText());
            
            if(nome.isBlank() || preco == 0 || quantidade == 0){
                throw new InvalidTypeException();
            }
            
            Produto p = new Produto();
            p.setNome(nome);
            p.setPreco(preco);
            p.setQuantidade(quantidade);
            
            Produtos.produtoDAO.cadastrar(p);
            
            return true;
        }catch(InvalidTypeException e1){
            JOptionPane.showMessageDialog(this, "Informe um valor em todos campos");
            return false;
        }catch(NumberFormatException e2){
            JOptionPane.showMessageDialog(this, "Preços devem ser informados no formato 00.00\nQuantidades devem ser números inteiros");
            return false;
        }
    }
    
}
