/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.produto;

import com.sun.jdi.InvalidTypeException;
import javax.swing.JOptionPane;
import model.Produto;

/**
 *
 * @author kauan
 */
public class EditarProduto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarProduto.class.getName());

    /**
     * Creates new form CadastroProdutos
     */
    public EditarProduto() {
        initComponents();
    }
    
    public EditarProduto(Produto produto) {
        initComponents();
        this.produto = produto;
        NomeField.setText(produto.getNome());
        PrecoField.setText(Double.toString(produto.getPreco()));
        QntField.setText(Integer.toString(produto.getQuantidade()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditarProdutoPanel = new javax.swing.JPanel();
        NomeField = new javax.swing.JTextField();
        PrecoField = new javax.swing.JTextField();
        QntField = new javax.swing.JTextField();
        NomeLabel = new javax.swing.JLabel();
        PrecoLabel = new javax.swing.JLabel();
        QntLabel = new javax.swing.JLabel();
        FinalizarButton = new javax.swing.JButton();
        TituloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        EditarProdutoPanel.setBackground(new java.awt.Color(206, 212, 218));

        NomeField.setBackground(new java.awt.Color(233, 236, 239));

        PrecoField.setBackground(new java.awt.Color(233, 236, 239));

        QntField.setBackground(new java.awt.Color(233, 236, 239));

        NomeLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        NomeLabel.setForeground(new java.awt.Color(52, 58, 64));
        NomeLabel.setText("Nome:");

        PrecoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PrecoLabel.setForeground(new java.awt.Color(52, 58, 64));
        PrecoLabel.setText("Preço:");

        QntLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        QntLabel.setForeground(new java.awt.Color(52, 58, 64));
        QntLabel.setText("Quantidade:");

        FinalizarButton.setBackground(new java.awt.Color(233, 236, 239));
        FinalizarButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FinalizarButton.setForeground(new java.awt.Color(52, 58, 64));
        FinalizarButton.setText("Finalizar");
        FinalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarButtonActionPerformed(evt);
            }
        });

        TituloLabel.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(52, 58, 64));
        TituloLabel.setText("Editar Produto");

        javax.swing.GroupLayout EditarProdutoPanelLayout = new javax.swing.GroupLayout(EditarProdutoPanel);
        EditarProdutoPanel.setLayout(EditarProdutoPanelLayout);
        EditarProdutoPanelLayout.setHorizontalGroup(
            EditarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarProdutoPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(EditarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FinalizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EditarProdutoPanelLayout.createSequentialGroup()
                        .addGroup(EditarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NomeLabel)
                            .addComponent(PrecoLabel)
                            .addComponent(QntLabel))
                        .addGap(72, 72, 72)
                        .addGroup(EditarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(PrecoField)
                            .addComponent(NomeField, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(QntField))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditarProdutoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EditarProdutoPanelLayout.setVerticalGroup(
            EditarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarProdutoPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TituloLabel)
                .addGap(77, 77, 77)
                .addGroup(EditarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomeLabel))
                .addGap(18, 18, 18)
                .addGroup(EditarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecoField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrecoLabel))
                .addGap(18, 18, 18)
                .addGroup(EditarProdutoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QntField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QntLabel))
                .addGap(18, 18, 18)
                .addComponent(FinalizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        NomeField.getAccessibleContext().setAccessibleName("Campo nome");
        NomeField.getAccessibleContext().setAccessibleDescription("Campo para informar o nome do produto");
        PrecoField.getAccessibleContext().setAccessibleName("Campo preço");
        PrecoField.getAccessibleContext().setAccessibleDescription("Campo para informar o preço do produto");
        QntField.getAccessibleContext().setAccessibleName("Campo quantidade");
        QntField.getAccessibleContext().setAccessibleDescription("Campo para informar a quantidade de produtos em estoque");
        TituloLabel.getAccessibleContext().setAccessibleDescription("Titulo da tela");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(EditarProdutoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditarProdutoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarButtonActionPerformed
        // TODO add your handling code here:
        editar();
        this.dispose();
    }//GEN-LAST:event_FinalizarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarProduto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EditarProdutoPanel;
    private javax.swing.JButton FinalizarButton;
    private javax.swing.JTextField NomeField;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JTextField PrecoField;
    private javax.swing.JLabel PrecoLabel;
    private javax.swing.JTextField QntField;
    private javax.swing.JLabel QntLabel;
    private javax.swing.JLabel TituloLabel;
    // End of variables declaration//GEN-END:variables
    Produto produto;
    
    void editar(){
        try{
            String nome = NomeField.getText();
            double preco = Double.parseDouble(PrecoField.getText());
            int quantidade = Integer.parseInt(QntField.getText());
            
            if(nome.isBlank() || preco == 0 || quantidade == 0){
                throw new InvalidTypeException();
            }
            
            produto.setNome(nome);
            produto.setPreco(preco);
            produto.setQuantidade(quantidade);
            
            Produtos.produtoDAO.atualizar(produto);
            
        }catch(InvalidTypeException e1){
            JOptionPane.showMessageDialog(this, "Informe um valor em todos campos");
        }catch(NumberFormatException e2){
            JOptionPane.showMessageDialog(this, "Preços devem ser informados no formato 00.00\nQuantidades devem ser números inteiros");
        }
    }
}

