/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.usuario;

import com.sun.jdi.InvalidTypeException;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author kauan
 */
public class CadastroUsuarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroUsuarios.class.getName());

    /**
     * Creates new form CadastroProdutos
     */
    public CadastroUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroUsuariosPanel = new javax.swing.JPanel();
        LoginField = new javax.swing.JTextField();
        SenhaField = new javax.swing.JTextField();
        LoginLabel = new javax.swing.JLabel();
        SenhaLabel = new javax.swing.JLabel();
        PermissoesLabel = new javax.swing.JLabel();
        CadastrarButton = new javax.swing.JButton();
        TituloLabel = new javax.swing.JLabel();
        PermissoesComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CadastroUsuariosPanel.setBackground(new java.awt.Color(206, 212, 218));

        LoginField.setBackground(new java.awt.Color(233, 236, 239));

        SenhaField.setBackground(new java.awt.Color(233, 236, 239));

        LoginLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(52, 58, 64));
        LoginLabel.setText("Login:");

        SenhaLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SenhaLabel.setForeground(new java.awt.Color(52, 58, 64));
        SenhaLabel.setText("Senha:");

        PermissoesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PermissoesLabel.setForeground(new java.awt.Color(52, 58, 64));
        PermissoesLabel.setText("Permissões:");

        CadastrarButton.setBackground(new java.awt.Color(233, 236, 239));
        CadastrarButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        CadastrarButton.setForeground(new java.awt.Color(52, 58, 64));
        CadastrarButton.setText("Cadastrar");
        CadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarButtonActionPerformed(evt);
            }
        });

        TituloLabel.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(52, 58, 64));
        TituloLabel.setText("Cadastrar Usuário");

        PermissoesComboBox.setBackground(new java.awt.Color(233, 236, 239));
        PermissoesComboBox.setForeground(new java.awt.Color(52, 58, 64));
        PermissoesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PADRAO", "GERENTE", "ADM" }));
        PermissoesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermissoesComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CadastroUsuariosPanelLayout = new javax.swing.GroupLayout(CadastroUsuariosPanel);
        CadastroUsuariosPanel.setLayout(CadastroUsuariosPanelLayout);
        CadastroUsuariosPanelLayout.setHorizontalGroup(
            CadastroUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroUsuariosPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(CadastroUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastroUsuariosPanelLayout.createSequentialGroup()
                        .addGroup(CadastroUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginLabel)
                            .addComponent(SenhaLabel)
                            .addComponent(PermissoesLabel))
                        .addGap(72, 72, 72)
                        .addGroup(CadastroUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SenhaField)
                            .addComponent(LoginField, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(PermissoesComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastroUsuariosPanelLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(TituloLabel)
                .addGap(182, 182, 182))
        );
        CadastroUsuariosPanelLayout.setVerticalGroup(
            CadastroUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastroUsuariosPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(TituloLabel)
                .addGap(77, 77, 77)
                .addGroup(CadastroUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginLabel))
                .addGap(18, 18, 18)
                .addGroup(CadastroUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SenhaLabel)
                    .addComponent(SenhaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastroUsuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PermissoesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PermissoesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(CadastrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        LoginField.getAccessibleContext().setAccessibleName("Campo login");
        LoginField.getAccessibleContext().setAccessibleDescription("Campo para informar o login");
        SenhaField.getAccessibleContext().setAccessibleName("Campo senha");
        SenhaField.getAccessibleContext().setAccessibleDescription("Campo para informar a senha");
        CadastrarButton.getAccessibleContext().setAccessibleName("Botão cadastrar");
        CadastrarButton.getAccessibleContext().setAccessibleDescription("Botão para finalizar o cadastro");
        TituloLabel.getAccessibleContext().setAccessibleDescription("Titulo da tela");
        PermissoesComboBox.getAccessibleContext().setAccessibleName("Permissões do usuário");
        PermissoesComboBox.getAccessibleContext().setAccessibleDescription("Campo para selecionar as permissões do usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastroUsuariosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CadastroUsuariosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PermissoesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermissoesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermissoesComboBoxActionPerformed

    private void CadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarButtonActionPerformed
        // TODO add your handling code here:
        if(cadastrar()){
            this.dispose();
        }
    }//GEN-LAST:event_CadastrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarButton;
    private javax.swing.JPanel CadastroUsuariosPanel;
    private javax.swing.JTextField LoginField;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JComboBox<String> PermissoesComboBox;
    private javax.swing.JLabel PermissoesLabel;
    private javax.swing.JTextField SenhaField;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JLabel TituloLabel;
    // End of variables declaration//GEN-END:variables

    boolean cadastrar(){
        try{
            Usuario usuario = new Usuario();
            
            if(LoginField.getText().isBlank() || SenhaField.getText().isBlank()){
                throw new InvalidTypeException();
            }
            
            usuario.setLogin(LoginField.getText());
            usuario.setSenha(SenhaField.getText());
            usuario.setPermissoes(PermissoesComboBox.getSelectedIndex());

            Usuarios.usuarioDAO.cadastrar(usuario);
            return true;
        }catch(InvalidTypeException e){
            JOptionPane.showMessageDialog(this, "Informe um valor em todos campos");
            return false;
        }
    }
}
