/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.usuario;

import com.sun.jdi.InvalidTypeException;
import javax.swing.JOptionPane;
import model.Usuario;

/**
 *
 * @author kauan
 */
public class EditarUsuario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarUsuario.class.getName());

    /**
     * Creates new form CadastroProdutos
     */
    public EditarUsuario() {
        initComponents();
    }
    
    public EditarUsuario(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        LoginField.setText(usuario.getLogin());
        SenhaField.setText(usuario.getSenha());
        PermissoesComboBox.setSelectedItem(usuario.getPermissoes().toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditarUsuarioPanel = new javax.swing.JPanel();
        LoginField = new javax.swing.JTextField();
        SenhaField = new javax.swing.JTextField();
        LoginLabel = new javax.swing.JLabel();
        SenhaLabel = new javax.swing.JLabel();
        PermissoesLabel = new javax.swing.JLabel();
        FinalizarButton = new javax.swing.JButton();
        TituloLabel = new javax.swing.JLabel();
        PermissoesComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        EditarUsuarioPanel.setBackground(new java.awt.Color(206, 212, 218));

        LoginField.setBackground(new java.awt.Color(233, 236, 239));

        SenhaField.setBackground(new java.awt.Color(233, 236, 239));

        LoginLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LoginLabel.setForeground(new java.awt.Color(52, 58, 64));
        LoginLabel.setText("Login:");

        SenhaLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        SenhaLabel.setForeground(new java.awt.Color(52, 58, 64));
        SenhaLabel.setText("Senha:");

        PermissoesLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PermissoesLabel.setForeground(new java.awt.Color(52, 58, 64));
        PermissoesLabel.setText("Permissões:");

        FinalizarButton.setBackground(new java.awt.Color(233, 236, 239));
        FinalizarButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FinalizarButton.setForeground(new java.awt.Color(52, 58, 64));
        FinalizarButton.setText("Finalizar");
        FinalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarButtonActionPerformed(evt);
            }
        });

        TituloLabel.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(52, 58, 64));
        TituloLabel.setText("Editar Usuário");

        PermissoesComboBox.setBackground(new java.awt.Color(233, 236, 239));
        PermissoesComboBox.setForeground(new java.awt.Color(52, 58, 64));
        PermissoesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PADRAO", "GERENTE", "ADM" }));
        PermissoesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermissoesComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditarUsuarioPanelLayout = new javax.swing.GroupLayout(EditarUsuarioPanel);
        EditarUsuarioPanel.setLayout(EditarUsuarioPanelLayout);
        EditarUsuarioPanelLayout.setHorizontalGroup(
            EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarUsuarioPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FinalizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EditarUsuarioPanelLayout.createSequentialGroup()
                        .addGroup(EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginLabel)
                            .addComponent(SenhaLabel)
                            .addComponent(PermissoesLabel))
                        .addGap(72, 72, 72)
                        .addGroup(EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloLabel)
                            .addGroup(EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SenhaField)
                                .addComponent(LoginField, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addComponent(PermissoesComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        EditarUsuarioPanelLayout.setVerticalGroup(
            EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditarUsuarioPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(TituloLabel)
                .addGap(74, 74, 74)
                .addGroup(EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginLabel))
                .addGap(18, 18, 18)
                .addGroup(EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SenhaLabel)
                    .addComponent(SenhaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EditarUsuarioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PermissoesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PermissoesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(FinalizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        LoginField.getAccessibleContext().setAccessibleName("Campo login");
        LoginField.getAccessibleContext().setAccessibleDescription("Campo para informar o login");
        SenhaField.getAccessibleContext().setAccessibleName("campo senha");
        SenhaField.getAccessibleContext().setAccessibleDescription("Campo para informar a senha");
        FinalizarButton.getAccessibleContext().setAccessibleName("Botão finalizar");
        FinalizarButton.getAccessibleContext().setAccessibleDescription("Botão para salvar as alteraçẽos feitas");
        TituloLabel.getAccessibleContext().setAccessibleDescription("Titulo da tela");
        PermissoesComboBox.getAccessibleContext().setAccessibleName("Selecionar permissões");
        PermissoesComboBox.getAccessibleContext().setAccessibleDescription("Campo para selecionar as permissões do usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditarUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EditarUsuarioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PermissoesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermissoesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermissoesComboBoxActionPerformed

    private void FinalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarButtonActionPerformed
        // TODO add your handling code here:
        editar();
        this.dispose();
    }//GEN-LAST:event_FinalizarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarUsuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EditarUsuarioPanel;
    private javax.swing.JButton FinalizarButton;
    private javax.swing.JTextField LoginField;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JComboBox<String> PermissoesComboBox;
    private javax.swing.JLabel PermissoesLabel;
    private javax.swing.JTextField SenhaField;
    private javax.swing.JLabel SenhaLabel;
    private javax.swing.JLabel TituloLabel;
    // End of variables declaration//GEN-END:variables
    Usuario usuario;
    
    void editar(){
        try{
            if(LoginField.getText().isBlank() || SenhaField.getText().isBlank()){
                throw new InvalidTypeException();
            }
            
            usuario.setLogin(LoginField.getText());
            usuario.setSenha(SenhaField.getText());
            usuario.setPermissoes(PermissoesComboBox.getSelectedIndex());
            
            Usuarios.usuarioDAO.atualizar(usuario);
        }catch(InvalidTypeException e1){
            JOptionPane.showMessageDialog(this, "Informe um valor em todos campos");
        }
    }   
}
