/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.usuario;

import view.produto.Produtos;
import java.awt.Color;
import javax.security.auth.login.LoginException;
import javax.swing.JOptionPane;
import model.Usuario;
import model.UsuarioDAO;

/**
 *
 * @author kauan
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginPanel = new javax.swing.JPanel();
        LoginField = new javax.swing.JTextField();
        SenhaField = new javax.swing.JTextField();
        EntrarButton = new javax.swing.JButton();
        TituloLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginPanel.setBackground(new java.awt.Color(206, 212, 218));

        LoginField.setBackground(new java.awt.Color(233, 236, 239));
        LoginField.setForeground(new java.awt.Color(173, 181, 189));
        LoginField.setText("Login");
        LoginField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LoginFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LoginFieldFocusLost(evt);
            }
        });
        LoginField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginFieldActionPerformed(evt);
            }
        });

        SenhaField.setBackground(new java.awt.Color(233, 236, 239));
        SenhaField.setForeground(new java.awt.Color(173, 181, 189));
        SenhaField.setText("Senha");
        SenhaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SenhaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SenhaFieldFocusLost(evt);
            }
        });

        EntrarButton.setBackground(new java.awt.Color(233, 236, 239));
        EntrarButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        EntrarButton.setForeground(new java.awt.Color(52, 58, 64));
        EntrarButton.setText("ENTRAR");
        EntrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarButtonActionPerformed(evt);
            }
        });

        TituloLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TituloLabel.setText("LOGIN");

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoginField)
                            .addComponent(SenhaField, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(EntrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                .addComponent(TituloLabel)
                .addGap(252, 252, 252))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TituloLabel)
                .addGap(60, 60, 60)
                .addComponent(LoginField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SenhaField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EntrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        LoginField.getAccessibleContext().setAccessibleName("Campo login");
        LoginField.getAccessibleContext().setAccessibleDescription("Campo para informar o login");
        SenhaField.getAccessibleContext().setAccessibleName("Campo senha ");
        SenhaField.getAccessibleContext().setAccessibleDescription("Campo para informar a senha");
        TituloLabel.getAccessibleContext().setAccessibleDescription("Titulo da tela");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginFieldActionPerformed

    private void EntrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarButtonActionPerformed
        // TODO add your handling code here:
        login();
        if(usuario != null){
            new Produtos().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_EntrarButtonActionPerformed

    private void LoginFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginFieldFocusGained
        // TODO add your handling code here:
        if(LoginField.getText().equals("Login")){
            LoginField.setText("");
            LoginField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_LoginFieldFocusGained

    private void LoginFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LoginFieldFocusLost
        // TODO add your handling code here:
        if(LoginField.getText().isBlank()){
            LoginField.setText("Login");
            LoginField.setForeground(new Color(173,181,189));
        }
    }//GEN-LAST:event_LoginFieldFocusLost

    private void SenhaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SenhaFieldFocusGained
        // TODO add your handling code here:
        if(SenhaField.getText().equals("Senha")){
            SenhaField.setText("");
            SenhaField.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_SenhaFieldFocusGained

    private void SenhaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SenhaFieldFocusLost
        // TODO add your handling code here:
        if(SenhaField.getText().isBlank()){
            SenhaField.setText("Senha");
            SenhaField.setForeground(new Color(173,181,189));
        }
    }//GEN-LAST:event_SenhaFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EntrarButton;
    private javax.swing.JTextField LoginField;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JTextField SenhaField;
    private javax.swing.JLabel TituloLabel;
    // End of variables declaration//GEN-END:variables
    public static Usuario usuario;
    UsuarioDAO usuarioDAO =  new UsuarioDAO();
    
    void login(){
        try{
            String login = LoginField.getText();
            String senha = SenhaField.getText();
            
            if(login.isEmpty() || senha.isEmpty()){
                JOptionPane.showMessageDialog(this, "Preencha todos os campos");
            }
            
            Usuario u = usuarioDAO.login(login, senha);
            this.usuario = u;
        }catch(LoginException e){
            JOptionPane.showMessageDialog(this, "Login e senha inválidos.\nTente novamente.");
            LoginField.setText("");
            SenhaField.setText("");
        }
    }
}
