/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.registro;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Entrada;
import model.EntradaDAO;
import model.Usuario;
import model.Venda;
import model.VendaDAO;
import util.ViewUtil;
import view.usuario.Login;

/**
 *
 * @author kauan
 */
public class Registros extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Registros.class.getName());

    /**
     * Creates new form Produtos
     */
    public Registros() {
        initComponents();
        switch (Login.usuario.getPermissoes()){
            case(Usuario.Permissoes.ADM):
                    break;
            case(Usuario.Permissoes.GERENTE):
                Usuários.setVisible(false);
                break;
            case(Usuario.Permissoes.PADRAO):
                Usuários.setVisible(false);
                RedEntradaButton.setVisible(false);
                ExcluirButton.setVisible(false);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VendasPanel = new javax.swing.JPanel();
        PesquisarField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        RegistrosTable = new javax.swing.JTable();
        ExcluirButton = new javax.swing.JButton();
        RegVendaButton = new javax.swing.JButton();
        RedEntradaButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        Produtos = new javax.swing.JMenuItem();
        Vendas = new javax.swing.JMenuItem();
        Usuários = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        VendasPanel.setBackground(new java.awt.Color(206, 212, 218));
        VendasPanel.setPreferredSize(new java.awt.Dimension(680, 450));

        PesquisarField.setBackground(new java.awt.Color(233, 236, 239));
        PesquisarField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PesquisarFieldKeyReleased(evt);
            }
        });

        RegistrosTable.setBackground(new java.awt.Color(233, 236, 239));
        RegistrosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Venda/Entrada", "Data", "Qnt. de produtos / Total"
            }
        ));
        jScrollPane1.setViewportView(RegistrosTable);
        RegistrosTable.getAccessibleContext().setAccessibleName("Tabela vendas");
        RegistrosTable.getAccessibleContext().setAccessibleDescription("tabela com vendas cadastradas");

        ExcluirButton.setBackground(new java.awt.Color(233, 236, 239));
        ExcluirButton.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        ExcluirButton.setText("Excluir");
        ExcluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirButtonActionPerformed(evt);
            }
        });

        RegVendaButton.setBackground(new java.awt.Color(233, 236, 239));
        RegVendaButton.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        RegVendaButton.setText("Registrar Venda");
        RegVendaButton.setToolTipText("");
        RegVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegVendaButtonActionPerformed(evt);
            }
        });

        RedEntradaButton.setBackground(new java.awt.Color(233, 236, 239));
        RedEntradaButton.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        RedEntradaButton.setText("<html> Registrar entrada<br/> de produtos<br /> </html>");
        RedEntradaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedEntradaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VendasPanelLayout = new javax.swing.GroupLayout(VendasPanel);
        VendasPanel.setLayout(VendasPanelLayout);
        VendasPanelLayout.setHorizontalGroup(
            VendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VendasPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PesquisarField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                    .addGroup(VendasPanelLayout.createSequentialGroup()
                        .addComponent(RegVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(RedEntradaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addComponent(ExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13))
        );
        VendasPanelLayout.setVerticalGroup(
            VendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VendasPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(PesquisarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(VendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VendasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ExcluirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RegVendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RedEntradaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PesquisarField.getAccessibleContext().setAccessibleName("Barra de pesquisa");
        PesquisarField.getAccessibleContext().setAccessibleDescription("campo para pesquisar usuários cadastrados");
        ExcluirButton.getAccessibleContext().setAccessibleDescription("botão para excluir registro selecionado");
        RegVendaButton.getAccessibleContext().setAccessibleDescription("botão para abrir tela de registro de vendas");
        RedEntradaButton.getAccessibleContext().setAccessibleDescription("botão para abrir registro da entrada de produtos");

        MenuBar.setPreferredSize(new java.awt.Dimension(25, 25));

        Menu.setText("Menu");

        Produtos.setText("Produtos");
        Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosActionPerformed(evt);
            }
        });
        Menu.add(Produtos);
        Produtos.getAccessibleContext().setAccessibleDescription("acessar tela de produtos");

        Vendas.setText("Registros");
        Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendasActionPerformed(evt);
            }
        });
        Menu.add(Vendas);
        Vendas.getAccessibleContext().setAccessibleDescription("acessar tela de vendas");

        Usuários.setText("Usuários");
        Usuários.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuáriosActionPerformed(evt);
            }
        });
        Menu.add(Usuários);
        Usuários.getAccessibleContext().setAccessibleDescription("acessar tela de usuários");

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Menu.add(Sair);
        Sair.getAccessibleContext().setAccessibleDescription("sair");

        MenuBar.add(Menu);
        Menu.getAccessibleContext().setAccessibleDescription("menu de telas");

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(VendasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VendasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegVendaButtonActionPerformed
        // TODO add your handling code here:
        new RegistrarVenda().setVisible(true);
    }//GEN-LAST:event_RegVendaButtonActionPerformed

    private void RedEntradaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedEntradaButtonActionPerformed
        // TODO add your handling code here:
        new RegistrarEntrada().setVisible(true);
    }//GEN-LAST:event_RedEntradaButtonActionPerformed

    private void ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosActionPerformed
        // TODO add your handling code here:
        ViewUtil.menuProdutos(this);
    }//GEN-LAST:event_ProdutosActionPerformed

    private void VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendasActionPerformed
        // TODO add your handling code here:
        ViewUtil.menuRegistros(this);
    }//GEN-LAST:event_VendasActionPerformed

    private void UsuáriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuáriosActionPerformed
        // TODO add your handling code here:
        ViewUtil.menuUsuarios(this);
    }//GEN-LAST:event_UsuáriosActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        ViewUtil.menuSair(this);
    }//GEN-LAST:event_SairActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        gerarTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void PesquisarFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesquisarFieldKeyReleased
        // TODO add your handling code here:
        ViewUtil.barraPesquisa(RegistrosTable, 1, PesquisarField);
    }//GEN-LAST:event_PesquisarFieldKeyReleased

    private void ExcluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirButtonActionPerformed
        // TODO add your handling code here:
        excluir();
        gerarTabela();
    }//GEN-LAST:event_ExcluirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Registros().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExcluirButton;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField PesquisarField;
    private javax.swing.JMenuItem Produtos;
    private javax.swing.JButton RedEntradaButton;
    private javax.swing.JButton RegVendaButton;
    private javax.swing.JTable RegistrosTable;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem Usuários;
    private javax.swing.JMenuItem Vendas;
    private javax.swing.JPanel VendasPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
   VendaDAO vendaDAO = new VendaDAO();
   EntradaDAO entradaDAO = new EntradaDAO();
   
    void gerarTabela(){
        DefaultTableModel model = (DefaultTableModel) RegistrosTable.getModel();
        model.setRowCount(0);
        try{
            List<Venda> vendas = vendaDAO.listar() != null ? vendaDAO.listar() : new ArrayList<>();
            List<Entrada> entradas = entradaDAO.listar() != null ? entradaDAO.listar() : new ArrayList<>();
            
            for(Venda v : vendas){
                String qntTotal = v.getQuantidade() + " / " + v.getTotal();
                model.addRow(new Object[]{
                    v.getId(),
                    v.tipoRegistro(),
                    v.getDataFormatada(),
                    qntTotal
                });
            }
            for(Entrada e : entradas){
                model.addRow(new Object [] {
                    e.getId(),
                    e.tipoRegistro(),
                    e.getDataFormatada(),
                    e.getQuantidade()
                });
            }
        }catch(Exception e){}
    }
    
    boolean excluir(){
        try{
            int linha = RegistrosTable.getSelectedRow();
            int id = (int) RegistrosTable.getValueAt(linha, 0);
            String tipo = (String) RegistrosTable.getValueAt(linha, 1);
            if(tipo.equals("Venda")){
                vendaDAO.excluir(id);
            }else if(tipo.equals("Entrada")){
                entradaDAO.excluir(id);
            }
            return true;
        }catch(IndexOutOfBoundsException e){
            JOptionPane.showMessageDialog(this, "Selecione um registro para excluir");
            return false;
        }
    }
}
