/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.registro;

import com.sun.jdi.InvalidTypeException;
import javax.swing.JOptionPane;
import model.Produto;
import model.ProdutoDAO;
import model.Venda;
import model.VendaDAO;

/**
 *
 * @author kauan
 */
public class RegistrarVenda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrarVenda.class.getName());

    /**
     * Creates new form RegistrarVenda
     */
    public RegistrarVenda() {
        initComponents();
        for(Produto p : produtoDAO.listar()){
            ProdutoComboBox.addItem(p.getNome());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrarVendaPanel = new javax.swing.JPanel();
        ProdutoComboBox = new javax.swing.JComboBox<>();
        QntField = new javax.swing.JTextField();
        DataField = new javax.swing.JTextField();
        ProdutoLabel = new javax.swing.JLabel();
        QntLabel = new javax.swing.JLabel();
        DataLabel = new javax.swing.JLabel();
        TituloLabel = new javax.swing.JLabel();
        FinalizarButton = new javax.swing.JButton();
        AdicionarButton = new javax.swing.JButton();
        TotalLabel = new javax.swing.JLabel();
        ValorTotalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        RegistrarVendaPanel.setBackground(new java.awt.Color(206, 212, 218));

        ProdutoComboBox.setBackground(new java.awt.Color(233, 236, 239));

        QntField.setBackground(new java.awt.Color(233, 236, 239));

        DataField.setBackground(new java.awt.Color(233, 236, 239));

        ProdutoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ProdutoLabel.setForeground(new java.awt.Color(52, 58, 64));
        ProdutoLabel.setText("Produto:");

        QntLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        QntLabel.setForeground(new java.awt.Color(52, 58, 64));
        QntLabel.setText("Quantidade:");

        DataLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        DataLabel.setForeground(new java.awt.Color(52, 58, 64));
        DataLabel.setText("Data:");

        TituloLabel.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(52, 58, 64));
        TituloLabel.setText("Registrar Venda");

        FinalizarButton.setBackground(new java.awt.Color(233, 236, 239));
        FinalizarButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        FinalizarButton.setForeground(new java.awt.Color(52, 58, 64));
        FinalizarButton.setText("Finalizar Venda");
        FinalizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarButtonActionPerformed(evt);
            }
        });

        AdicionarButton.setBackground(new java.awt.Color(233, 236, 239));
        AdicionarButton.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        AdicionarButton.setForeground(new java.awt.Color(52, 58, 64));
        AdicionarButton.setText("Adicionar Item");
        AdicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarButtonActionPerformed(evt);
            }
        });

        TotalLabel.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        TotalLabel.setText("Total: R$");

        ValorTotalLabel.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        ValorTotalLabel.setText("00.00");

        javax.swing.GroupLayout RegistrarVendaPanelLayout = new javax.swing.GroupLayout(RegistrarVendaPanel);
        RegistrarVendaPanel.setLayout(RegistrarVendaPanelLayout);
        RegistrarVendaPanelLayout.setHorizontalGroup(
            RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarVendaPanelLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(TituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarVendaPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProdutoLabel)
                    .addComponent(QntLabel)
                    .addComponent(DataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(QntField)
                        .addComponent(ProdutoComboBox, 0, 350, Short.MAX_VALUE)
                        .addComponent(DataField))
                    .addGroup(RegistrarVendaPanelLayout.createSequentialGroup()
                        .addComponent(AdicionarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrarVendaPanelLayout.createSequentialGroup()
                                .addComponent(TotalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ValorTotalLabel))
                            .addComponent(FinalizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );
        RegistrarVendaPanelLayout.setVerticalGroup(
            RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarVendaPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(TituloLabel)
                .addGap(59, 59, 59)
                .addGroup(RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProdutoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProdutoLabel))
                .addGap(18, 18, 18)
                .addGroup(RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QntField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QntLabel))
                .addGap(18, 18, 18)
                .addGroup(RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataLabel))
                .addGap(27, 27, 27)
                .addGroup(RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FinalizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AdicionarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarVendaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorTotalLabel))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        ProdutoComboBox.getAccessibleContext().setAccessibleName("Selecionar produto");
        ProdutoComboBox.getAccessibleContext().setAccessibleDescription("Campo para selecionar o produto");
        QntField.getAccessibleContext().setAccessibleName("Campo quantidade");
        QntField.getAccessibleContext().setAccessibleDescription("Campo para informar quanto do produto informado foi vendido");
        DataField.getAccessibleContext().setAccessibleName("Campo venda");
        DataField.getAccessibleContext().setAccessibleDescription("Campo para informar a data da venda");
        TituloLabel.getAccessibleContext().setAccessibleDescription("Titulo da tela");
        FinalizarButton.getAccessibleContext().setAccessibleName("Botão finalizar venda");
        FinalizarButton.getAccessibleContext().setAccessibleDescription("Botão para finalizar o registro da venda");
        AdicionarButton.getAccessibleContext().setAccessibleName("Botão adicionar item");
        AdicionarButton.getAccessibleContext().setAccessibleDescription("Botão para adicionar ao registro outro produto que foi vendido ");
        TotalLabel.getAccessibleContext().setAccessibleName("Total");
        TotalLabel.getAccessibleContext().setAccessibleDescription("");
        ValorTotalLabel.getAccessibleContext().setAccessibleName("Valor total");
        ValorTotalLabel.getAccessibleContext().setAccessibleDescription("valor total da venda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RegistrarVendaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RegistrarVendaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarButtonActionPerformed
        // TODO add your handling code here:
        registrar();
        ProdutoComboBox.setSelectedIndex(0);
        QntField.setText("");
        DataField.setEditable(false);
    }//GEN-LAST:event_AdicionarButtonActionPerformed

    private void FinalizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarButtonActionPerformed
        // TODO add your handling code here:
        registrar();
        vendaDAO.cadastrar(venda);
        this.dispose();
    }//GEN-LAST:event_FinalizarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrarVenda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarButton;
    private javax.swing.JTextField DataField;
    private javax.swing.JLabel DataLabel;
    private javax.swing.JButton FinalizarButton;
    private javax.swing.JComboBox<String> ProdutoComboBox;
    private javax.swing.JLabel ProdutoLabel;
    private javax.swing.JTextField QntField;
    private javax.swing.JLabel QntLabel;
    private javax.swing.JPanel RegistrarVendaPanel;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel ValorTotalLabel;
    // End of variables declaration//GEN-END:variables
    Venda venda = new Venda();
    ProdutoDAO produtoDAO = new ProdutoDAO();
    VendaDAO vendaDAO = new VendaDAO();
    
    boolean registrar(){
        try{
            int selecionado = ProdutoComboBox.getSelectedIndex();
            Produto produto = produtoDAO.listar().get(selecionado);

            String data = DataField.getText();
            String formato = "^([0-2][0-9]|3[01])/(0[1-9]|1[0-2])/([0-9]{4})$";
            int quantidade = Integer.parseInt(QntField.getText());
            double totalItem = produto.getPreco() * quantidade;

            if (quantidade > produto.getQuantidade()) {
                throw new InvalidTypeException("quantidade maior");
            } else if (!data.matches(formato)) {
                throw new InvalidTypeException("data");
            } else if (quantidade < 0) {
                throw new InvalidTypeException("quantidade < 0");
            } else if (quantidade == 0) {
                throw new InvalidTypeException("quantidade == 0");
            } else if (QntField.getText().isBlank() || DataField.getText().isBlank()) {
                throw new InvalidTypeException("campo vazio");
            }

            venda.addProduto(produto);
            venda.setDataString(data);
            venda.setQuantidade(venda.getQuantidade() + quantidade);
            venda.setTotal(venda.getTotal() + totalItem);

            produto.setQuantidade(produto.getQuantidade() - quantidade);
            produtoDAO.atualizar(produto);

            ValorTotalLabel.setText(Double.toString(venda.getTotal()));

            return true;
        }catch(InvalidTypeException e1){
            switch(e1.getMessage()){
                case("quantidade maior"):
                    JOptionPane.showMessageDialog(this, "Número de produtos indísponível;\nInforme uma quantidade menor ou registre o reabastecimento de produtos.");
                break;
                case("data"):
                    JOptionPane.showMessageDialog(this, "Informe a data no formato dd/MM/aaaa (data/mês/ano)");
                break;
                case("quantidade < 0"):
                    JOptionPane.showMessageDialog(this, "O número de produtos vendidos não pode ser menor que 0");
                break;
                case("quantidade == 0"):
                    JOptionPane.showMessageDialog(this, "O número de produtos vendidos não pode ser igual a 0");
                break;
                case("campo vazio"):
                    JOptionPane.showMessageDialog(this, "Devem ser informados valores em todos os campos");
                break;
            }
            return false;
        }catch(NumberFormatException e2){
            JOptionPane.showMessageDialog(this, "Quantidades devem ser registradas como números inteiros");
            return false;
        }
    }

}
